version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: siem
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  collector:
    build: ./collector
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/siem
    ports:
      - "8000:8000"

volumes:
  db_data:
